### ISSUE TITLE
github.io pages 搭建

### ISSUE THREAD

**Issue by junxnone** [junxnone/wiki#37]
# TO-DO
- [x] Jekyll 搭建blog
- [x] 更改 Jekyll 主题
- [x] Github issues 作为文章
- [x] Backup Github repos & Issues

# Reference
- [ ] [免费顶级域名+github个人主页教程](https://blog.csdn.net/lyp_hy/article/details/82116255)
- [ ] [参考wiki](https://ctf-wiki.github.io/ctf-wiki/)
- [x] [Mirror - 基于 issues 的博客工具](https://mirror.am0200.com/#/posts/11)
  - [x] [Mirror ](https://github.com/LoeiFy/Mirror)
- [ ] [python-github-backup](https://github.com/josegonzalez/python-github-backup)

# 设置 github io page
1. 新建 repo : xxx.github.io
2. 新建Readme.md
3. 选择theme
## 设置title/description/google analytics

# domain
## 设置Custom domain
```
www.xxx.xx
```
> 如果不添加www，解析会错误. why?

## 可以设置短网址跳转 URL Forwarding

- **URL Redirect**: When you use this forwarding type, a person typing your domain on the  browser (for example: www.yourdomain.com) gets redirected to the actual  web server where your web pages are hosted on (for  example:home.yourwebserver.com/yourdomain). However, after the  redirection, the browser's address bar will display the location of the  actual web page (home.yourwebserver.com/yourdomain) instead of  your domain name (www.yourdomain.com).
- **URL Frame**: This works similar to URL redirect type except that instead of redirecting the visitor to your web page, the web page is displayed in a frame from the server. The difference is that after redirection, the browser's address bar will continue to display your domain name (for example: www.yourdomain.com) in the browser's address bar instead of the actual location of the webpage.

# Jekyll plugins

**Comment by junxnone** [comment]
#56
